apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc01
  namespace: nisha
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: ""
  selector:
    matchLabels:
      pvname: pv01
